---
- name: Install MongoDB server onto VM PROVISIONED FROM VAGRANT BOX ansible_4640
  become: yes
  package:
    name: mongodb-server
    state: installed
- name: Enable and start MongoDB server on VM PROVISIONED FROM VAGRANT BOX ansible_4640
  become: yes
  service:
    name: mongod
    enabled: yes
    state: started