---   
- name: Create todoapp user
  become: yes
  user:
    name: "{{todoapp_user_name}}"
    password: "{{todoapp_user_password}}"
- name: Install git
  become: yes
  package:
      name: git
      state: installed
- name: Clone git 
  become: yes
  git:
    repo: "{{web_app_repository}}"
    dest: "/home/{{todoapp_user_name}}/app"
- name: Run npm install
  become: yes
  npm:
    path: "/home/{{todoapp_user_name}}/app"
- name: Using database.js template
  become: yes
  template:
    src: database.j2
    dest: "/home/{{todoapp_user_name}}/app/config/database.js"
- name: Apply permissions
  become: yes
  file:
    path: "/home/{{todoapp_user_name}}"
    state: directory
    recurse: yes
    mode: '0755'
    owner: "{{todoapp_user_name}}"
    group: "{{todoapp_user_name}}"
- name: Move todoapp.service file with template
  become: yes
  template:
    src: todoapp_service.j2
    dest: /lib/systemd/system/todoapp.service
- name: Reload daemons
  become: yes
  systemd:
    daemon_reload: yes
- name: Enable and start todoapp
  become: yes
  service:
    name: todoapp
    enabled: yes
    state: started