---
- name: Open http port
  become: yes
  firewalld:
    service: http
    zone: public
    permanent: yes
    state: enabled
    immediate: yes
- name: Open https port
  become: yes
  firewalld:
    service: https
    zone: public
    permanent: yes
    state: enabled
    immediate: yes
- name: Install nginx
  become: yes
  package:
    name: nginx
    state: installed
- name: Move modified nginx config file to server with template
  become: yes
  template:
    src: nginx_conf.j2
    dest: /etc/nginx/nginx.conf
- name: Set nginx config file ownership
  become: yes
  file:
    path: /etc/nginx/nginx.conf
    owner: nginx
    group: nginx
- name: Reload nginx configuration file
  become: yes
  service:
    name: nginx
    state: reloaded
    enabled: yes