Vagrant.configure("2") do |config|
  config.vm.box = "ansible_4640.box"

  config.ssh.username = "admin"
  config.ssh.private_key_path = "./files/admin_id_rsa"

  config.vm.define "todoapp" do |todoapp|
    todoapp.vm.hostname = "todoapp.bcit.local"
    todoapp.vm.network "forwarded_port", guest: 80, host: 50080
    todoapp.vm.synced_folder ".", "/vagrant", disabled: true
    todoapp.vm.provision :ansible do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ansible/todoapp.yml"
      ansible.inventory_path = "ansible/hosts"
    end
    todoapp.vm.provider "virtualbox" do |vb|
      vb.name = "TODO_4640"
      vb.linked_clone = true
    end
  end

end