---
- hosts: todoapp
  tasks:
    - name: Include the role 'base'
      include_role:
        name: base
    - name: Include the role 'todoapp'
      include_role:
        name: todoapp

    