---
- hosts: todoapp
  tasks:
    - name: Use role 'base' for system configuration
      include_role:
        name: base
    - name: Use role 'todoapp' to setup todoapp user and service
      include_role:
        name: todoapp

    