---
- hosts: todoapp
  vars:
    todoapp_user_name: todo-app
    todoapp_user_password: $6$PZ.ykpkylLrd$qT.M5Esjr7ndvGba3H9v5paqglzLLiKMQK07Hlr.OnNwyiGAMev7mUCkHtvpsJ9yNNrpC/rXNsPrXDgIFcA91/
    web_app_repository: https://github.com/timoguic/ACIT4640-todo-app.git
  tasks:
    - name: Open http port
      become: yes
      firewalld:
        service: http
        zone: public
        permanent: yes
        state: enabled
        immediate: yes
    - name: Open https port
      become: yes
      firewalld:
        service: https
        zone: public
        permanent: yes
        state: enabled
        immediate: yes
    - name: Open ssh port
      become: yes
      firewalld:
        service: ssh
        zone: public
        permanent: yes
        state: enabled
        immediate: yes
    - name: Disable SELinux
      become: yes
      selinux:
        state: disabled
    - name: Create todoapp user
      become: yes
      user:
        name: "{{todoapp_user_name}}"
        password: "{{todoapp_user_password}}"
    - name: Install MongoDB server
      become: yes
      package:
        name: mongodb-server
        state: installed
    - name: Enable and start MongoDB server
      become: yes
      service:
        name: mongod
        enabled: yes
        state: started
    - name: Install NodeJS
      become: yes
      package:
          name: nodejs
          state: installed
    - name: Install git
      become: yes
      package:
          name: git
          state: installed
    - name: Clone git 
      become: yes
      git:
        repo: "{{web_app_repository}}"
        dest: "/home/{{todoapp_user_name}}/app"
    - name: Run npm install
      become: yes
      npm:
        path: "/home/{{todoapp_user_name}}/app"
    - name: Copy database.js file
      become: yes
      copy:
        src: ../files/database.js
        dest: "/home/{{todoapp_user_name}}/app/config/database.js"
    - name: Apply permissions
      become: yes
      file:
        path: "/home/{{todoapp_user_name}}"
        state: directory
        recurse: yes
        mode: '0755'
        owner: "{{todoapp_user_name}}"
        group: "{{todoapp_user_name}}"
    - name: Install nginx
      become: yes
      package:
        name: nginx
        state: installed
    - name: Copy nginx config files
      become: yes
      copy:
        src: ../files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: nginx
        group: nginx
    - name: Reload nginx configuration file
      become: yes
      service:
        name: nginx
        state: reloaded
        enabled: yes
    - name: Copy todoapp.service file
      become: yes
      copy:
        src: ../files/todoapp.service
        dest: /lib/systemd/system/todoapp.service
    - name: Reload daemons
      become: yes
      systemd:
        daemon_reload: yes
    - name: Enable and start todoapp
      become: yes
      service:
        name: todoapp
        enabled: yes
        state: started